apiVersion: external-secrets.io/v1beta1
kind: ExternalSecret
metadata:
  name: aws-openshift-mysecret02
spec:
  refreshInterval: 1m
  secretStoreRef:
    name: secretstore-aws
    kind: SecretStore
  target:
    name: aws-openshift-mysecret02
  data:
  - secretKey: privatedata
    remoteRef:
      key: openshift-mysecret02